# TRACING-settings
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
      #url: http://${JAEGER_HOST}:14268/api/traces
    #enable-b3-propagation: true
spring:
  application:
    name: apiexperiencia
    
sample:
 property: test
server:
 beneficioDescuentoURL: http://localhost:8081/beneficios/descuentos/clientePlanilla
