
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
      
spring:
  application:
    name: apiexperiencia
    
server:
 beneficioDescuentoURL: http://localhost:8081/beneficios/descuentos/clientePlanilla
