opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
      #url: http://${JAEGER_HOST}:14268/api/traces
    #enable-b3-propagation: true
spring:
  application:
    name: beneficiodescuento
logging:
  level:
    io.opentracing: DEBUG
    
sample:
 property: BeneficioDescuento
server:
 promocionURL: http://poc-promocion:4040/api/v1/Comercios/
 clienteURL1: http://localhost:7777/credit-charge-card/sd-reference-id/credit-charge-card-fulfilment-arrangement/
 clienteURL2: http://localhost:7777/customer-reference-data-management/sd-reference-id/customer-reference-data-directory-entry/
 clienteURL3: http://ef78810566a5.ngrok.io/party-data-management/sd-reference-id/party-directory-entry/6105078
